import { allFeatureDetails } from "content-collections";
import type { ElementType } from "react";
import {
	AdminIcon,
	CalculatorMinimalisticIcon,
	CalendarIcon,
	CapIcon,
	Chart2Icon,
	ChatUnreadIcon,
	ClapperboardPlayIcon,
	ClipboardListIcon,
	CupStarIcon,
	DialogIcon,
	DiamondIcon,
	DiplomaIcon,
	FileIcon,
	GraphNewUpIcon,
	HeadphoneIcon,
	InfoIcon,
	ListIcon,
	NotebookBookmarkIcon,
	NotebookSquareIcon,
	PieChart3Icon,
	SidebarIcon,
	StarIcon,
	StarsIcon,
	TeacherIcon,
	TestTubeIcon,
	UserBlockIcon,
	UserGroupRoundedIcon,
	UserHeartRoundedIcon,
	UserSpeakRoundedIcon,
	UsersGroupTwoRoundedIcon,
	VisaIcon,
	Widget6Icon,
	WindowFrameIcon,
} from "@/assets/icons";
import { AnalyzIcon } from "@/assets/icons/analyz-icon";
import { BuildIcon } from "@/assets/icons/build-icon";
import { RoutingIcon } from "@/assets/icons/routing-icons";
import { StructureIcon } from "@/assets/icons/structure-icon";

export const NAV_FEATURE_ICON_KEYS = [
	"notebookBookmark",
	"userSpeakRounded",
	"notebookSquare",
	"testTube",
	"calculatorMinimalistic",
	"clipboardList",
	"diploma",
	"clapperboardPlay",
	"routing",
	"usersGroupTwoRounded",
	"dialog",
	"chatUnread",
	"star",
	"calendar",
	"userHeartRounded",
	"sidebar",
	"windowFrame",
	"userGroupRounded",
	"stars",
	"userBlock",
	"pieChart3",
	"chart2",
	"cupStar",
	"widget6",
	"graphNewUp",
	"build",
	"structure",
	"diamond",
	"teacher",
	"headphone",
	"analyz",
	"cap",
	"visa",
	"info",
	"list",
	"admin",
	"file",
] as const;

export type NavFeatureIconKey = (typeof NAV_FEATURE_ICON_KEYS)[number];

export const NAV_FEATURE_ICON_MAP: Record<NavFeatureIconKey, ElementType> = {
	notebookBookmark: NotebookBookmarkIcon,
	userSpeakRounded: UserSpeakRoundedIcon,
	notebookSquare: NotebookSquareIcon,
	testTube: TestTubeIcon,
	calculatorMinimalistic: CalculatorMinimalisticIcon,
	clipboardList: ClipboardListIcon,
	diploma: DiplomaIcon,
	clapperboardPlay: ClapperboardPlayIcon,
	routing: RoutingIcon,
	usersGroupTwoRounded: UsersGroupTwoRoundedIcon,
	dialog: DialogIcon,
	chatUnread: ChatUnreadIcon,
	star: StarIcon,
	calendar: CalendarIcon,
	userHeartRounded: UserHeartRoundedIcon,
	sidebar: SidebarIcon,
	windowFrame: WindowFrameIcon,
	userGroupRounded: UserGroupRoundedIcon,
	stars: StarsIcon,
	userBlock: UserBlockIcon,
	pieChart3: PieChart3Icon,
	chart2: Chart2Icon,
	cupStar: CupStarIcon,
	widget6: Widget6Icon,
	graphNewUp: GraphNewUpIcon,
	build: BuildIcon,
	structure: StructureIcon,
	diamond: DiamondIcon,
	teacher: TeacherIcon,
	headphone: HeadphoneIcon,
	analyz: AnalyzIcon,
	cap: CapIcon,
	visa: VisaIcon,
	info: InfoIcon,
	list: ListIcon,
	admin: AdminIcon,
	file: FileIcon,
};

export function resolveNavFeatureIcon(
	slugOrId: string,
): ElementType | undefined {
	const doc = allFeatureDetails.find(
		(d) => d.slug === slugOrId || d.id === slugOrId,
	);
	if (!doc?.navIcon) return undefined;
	return NAV_FEATURE_ICON_MAP[doc.navIcon as NavFeatureIconKey];
}
