/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestDemoRouteImport } from './routes/request-demo'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ContactSalesRouteImport } from './routes/contact-sales'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as IntegrationsSlugRouteImport } from './routes/integrations.$slug'
import { Route as FeaturesSlugRouteImport } from './routes/features.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const RequestDemoRoute = RequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSalesRoute = ContactSalesRouteImport.update({
  id: '/contact-sales',
  path: '/contact-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IntegrationsRoute,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRoute,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogsRoute,
} as any)
const IntegrationsSlugRoute = IntegrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IntegrationsRoute,
} as any)
const FeaturesSlugRoute = FeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FeaturesRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact-sales': typeof ContactSalesRoute
  '/contact-us': typeof ContactUsRoute
  '/features': typeof FeaturesRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/api/contact': typeof ApiContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact-sales': typeof ContactSalesRoute
  '/contact-us': typeof ContactUsRoute
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/api/contact': typeof ApiContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/blogs': typeof BlogsIndexRoute
  '/features': typeof FeaturesIndexRoute
  '/integrations': typeof IntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact-sales': typeof ContactSalesRoute
  '/contact-us': typeof ContactUsRoute
  '/features': typeof FeaturesRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/request-demo': typeof RequestDemoRoute
  '/api/contact': typeof ApiContactRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/features/$slug': typeof FeaturesSlugRoute
  '/integrations/$slug': typeof IntegrationsSlugRoute
  '/blogs/': typeof BlogsIndexRoute
  '/features/': typeof FeaturesIndexRoute
  '/integrations/': typeof IntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/contact-sales'
    | '/contact-us'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/request-demo'
    | '/api/contact'
    | '/blogs/$slug'
    | '/features/$slug'
    | '/integrations/$slug'
    | '/blogs/'
    | '/features/'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact-sales'
    | '/contact-us'
    | '/pricing'
    | '/request-demo'
    | '/api/contact'
    | '/blogs/$slug'
    | '/features/$slug'
    | '/integrations/$slug'
    | '/blogs'
    | '/features'
    | '/integrations'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/contact-sales'
    | '/contact-us'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/request-demo'
    | '/api/contact'
    | '/blogs/$slug'
    | '/features/$slug'
    | '/integrations/$slug'
    | '/blogs/'
    | '/features/'
    | '/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactSalesRoute: typeof ContactSalesRoute
  ContactUsRoute: typeof ContactUsRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  PricingRoute: typeof PricingRoute
  RequestDemoRoute: typeof RequestDemoRoute
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-demo': {
      id: '/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof RequestDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-sales': {
      id: '/contact-sales'
      path: '/contact-sales'
      fullPath: '/contact-sales'
      preLoaderRoute: typeof ContactSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/features/': {
      id: '/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/integrations/$slug': {
      id: '/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof IntegrationsSlugRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/features/$slug': {
      id: '/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof FeaturesSlugRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
  BlogsIndexRoute: BlogsIndexRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface FeaturesRouteChildren {
  FeaturesSlugRoute: typeof FeaturesSlugRoute
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesSlugRoute: FeaturesSlugRoute,
  FeaturesIndexRoute: FeaturesIndexRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsSlugRoute: typeof IntegrationsSlugRoute
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsSlugRoute: IntegrationsSlugRoute,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactSalesRoute: ContactSalesRoute,
  ContactUsRoute: ContactUsRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  PricingRoute: PricingRoute,
  RequestDemoRoute: RequestDemoRoute,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
