/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as PublicTermsOfServiceRouteImport } from './routes/_public/terms-of-service'
import { Route as PublicRequestDemoRouteImport } from './routes/_public/request-demo'
import { Route as PublicPrivacyPolicyRouteImport } from './routes/_public/privacy-policy'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as PublicIntegrationsRouteImport } from './routes/_public/integrations'
import { Route as PublicFeaturesRouteImport } from './routes/_public/features'
import { Route as PublicCookiePolicyRouteImport } from './routes/_public/cookie-policy'
import { Route as PublicContactUsRouteImport } from './routes/_public/contact-us'
import { Route as PublicContactSalesRouteImport } from './routes/_public/contact-sales'
import { Route as PublicBlogsRouteImport } from './routes/_public/blogs'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthNewPasswordRouteImport } from './routes/_auth/new-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordOtpRouteImport } from './routes/_auth/forgot-password-otp'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as PublicIntegrationsIndexRouteImport } from './routes/_public/integrations.index'
import { Route as PublicFeaturesIndexRouteImport } from './routes/_public/features.index'
import { Route as PublicBlogsIndexRouteImport } from './routes/_public/blogs.index'
import { Route as PublicIntegrationsSlugRouteImport } from './routes/_public/integrations.$slug'
import { Route as PublicFeaturesSlugRouteImport } from './routes/_public/features.$slug'
import { Route as PublicBlogsSlugRouteImport } from './routes/_public/blogs.$slug'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsOfServiceRoute = PublicTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicRequestDemoRoute = PublicRequestDemoRouteImport.update({
  id: '/request-demo',
  path: '/request-demo',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPrivacyPolicyRoute = PublicPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicIntegrationsRoute = PublicIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicFeaturesRoute = PublicFeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCookiePolicyRoute = PublicCookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactUsRoute = PublicContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicContactSalesRoute = PublicContactSalesRouteImport.update({
  id: '/contact-sales',
  path: '/contact-sales',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBlogsRoute = PublicBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/new-password',
  path: '/new-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordOtpRoute = AuthForgotPasswordOtpRouteImport.update({
  id: '/forgot-password-otp',
  path: '/forgot-password-otp',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const PublicIntegrationsIndexRoute = PublicIntegrationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicIntegrationsRoute,
} as any)
const PublicFeaturesIndexRoute = PublicFeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicFeaturesRoute,
} as any)
const PublicBlogsIndexRoute = PublicBlogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicBlogsRoute,
} as any)
const PublicIntegrationsSlugRoute = PublicIntegrationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicIntegrationsRoute,
} as any)
const PublicFeaturesSlugRoute = PublicFeaturesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicFeaturesRoute,
} as any)
const PublicBlogsSlugRoute = PublicBlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicBlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/forgot-password-otp': typeof AuthForgotPasswordOtpRoute
  '/login': typeof AuthLoginRoute
  '/new-password': typeof AuthNewPasswordRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/blogs': typeof PublicBlogsRouteWithChildren
  '/contact-sales': typeof PublicContactSalesRoute
  '/contact-us': typeof PublicContactUsRoute
  '/cookie-policy': typeof PublicCookiePolicyRoute
  '/features': typeof PublicFeaturesRouteWithChildren
  '/integrations': typeof PublicIntegrationsRouteWithChildren
  '/pricing': typeof PublicPricingRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/request-demo': typeof PublicRequestDemoRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/api/contact': typeof ApiContactRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/blogs/$slug': typeof PublicBlogsSlugRoute
  '/features/$slug': typeof PublicFeaturesSlugRoute
  '/integrations/$slug': typeof PublicIntegrationsSlugRoute
  '/blogs/': typeof PublicBlogsIndexRoute
  '/features/': typeof PublicFeaturesIndexRoute
  '/integrations/': typeof PublicIntegrationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/forgot-password-otp': typeof AuthForgotPasswordOtpRoute
  '/login': typeof AuthLoginRoute
  '/new-password': typeof AuthNewPasswordRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/contact-sales': typeof PublicContactSalesRoute
  '/contact-us': typeof PublicContactUsRoute
  '/cookie-policy': typeof PublicCookiePolicyRoute
  '/pricing': typeof PublicPricingRoute
  '/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/request-demo': typeof PublicRequestDemoRoute
  '/terms-of-service': typeof PublicTermsOfServiceRoute
  '/api/contact': typeof ApiContactRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/blogs/$slug': typeof PublicBlogsSlugRoute
  '/features/$slug': typeof PublicFeaturesSlugRoute
  '/integrations/$slug': typeof PublicIntegrationsSlugRoute
  '/blogs': typeof PublicBlogsIndexRoute
  '/features': typeof PublicFeaturesIndexRoute
  '/integrations': typeof PublicIntegrationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/forgot-password-otp': typeof AuthForgotPasswordOtpRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/new-password': typeof AuthNewPasswordRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_public/blogs': typeof PublicBlogsRouteWithChildren
  '/_public/contact-sales': typeof PublicContactSalesRoute
  '/_public/contact-us': typeof PublicContactUsRoute
  '/_public/cookie-policy': typeof PublicCookiePolicyRoute
  '/_public/features': typeof PublicFeaturesRouteWithChildren
  '/_public/integrations': typeof PublicIntegrationsRouteWithChildren
  '/_public/pricing': typeof PublicPricingRoute
  '/_public/privacy-policy': typeof PublicPrivacyPolicyRoute
  '/_public/request-demo': typeof PublicRequestDemoRoute
  '/_public/terms-of-service': typeof PublicTermsOfServiceRoute
  '/api/contact': typeof ApiContactRoute
  '/_public/': typeof PublicIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_public/blogs/$slug': typeof PublicBlogsSlugRoute
  '/_public/features/$slug': typeof PublicFeaturesSlugRoute
  '/_public/integrations/$slug': typeof PublicIntegrationsSlugRoute
  '/_public/blogs/': typeof PublicBlogsIndexRoute
  '/_public/features/': typeof PublicFeaturesIndexRoute
  '/_public/integrations/': typeof PublicIntegrationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/forgot-password-otp'
    | '/login'
    | '/new-password'
    | '/register'
    | '/verify-email'
    | '/blogs'
    | '/contact-sales'
    | '/contact-us'
    | '/cookie-policy'
    | '/features'
    | '/integrations'
    | '/pricing'
    | '/privacy-policy'
    | '/request-demo'
    | '/terms-of-service'
    | '/api/contact'
    | '/onboarding/'
    | '/blogs/$slug'
    | '/features/$slug'
    | '/integrations/$slug'
    | '/blogs/'
    | '/features/'
    | '/integrations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/forgot-password-otp'
    | '/login'
    | '/new-password'
    | '/register'
    | '/verify-email'
    | '/contact-sales'
    | '/contact-us'
    | '/cookie-policy'
    | '/pricing'
    | '/privacy-policy'
    | '/request-demo'
    | '/terms-of-service'
    | '/api/contact'
    | '/onboarding'
    | '/blogs/$slug'
    | '/features/$slug'
    | '/integrations/$slug'
    | '/blogs'
    | '/features'
    | '/integrations'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/onboarding'
    | '/_auth/forgot-password'
    | '/_auth/forgot-password-otp'
    | '/_auth/login'
    | '/_auth/new-password'
    | '/_auth/register'
    | '/_auth/verify-email'
    | '/_public/blogs'
    | '/_public/contact-sales'
    | '/_public/contact-us'
    | '/_public/cookie-policy'
    | '/_public/features'
    | '/_public/integrations'
    | '/_public/pricing'
    | '/_public/privacy-policy'
    | '/_public/request-demo'
    | '/_public/terms-of-service'
    | '/api/contact'
    | '/_public/'
    | '/onboarding/'
    | '/_public/blogs/$slug'
    | '/_public/features/$slug'
    | '/_public/integrations/$slug'
    | '/_public/blogs/'
    | '/_public/features/'
    | '/_public/integrations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
  ApiContactRoute: typeof ApiContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms-of-service': {
      id: '/_public/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof PublicTermsOfServiceRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/request-demo': {
      id: '/_public/request-demo'
      path: '/request-demo'
      fullPath: '/request-demo'
      preLoaderRoute: typeof PublicRequestDemoRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/privacy-policy': {
      id: '/_public/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PublicPrivacyPolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/integrations': {
      id: '/_public/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof PublicIntegrationsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/features': {
      id: '/_public/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof PublicFeaturesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/cookie-policy': {
      id: '/_public/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof PublicCookiePolicyRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact-us': {
      id: '/_public/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicContactUsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/contact-sales': {
      id: '/_public/contact-sales'
      path: '/contact-sales'
      fullPath: '/contact-sales'
      preLoaderRoute: typeof PublicContactSalesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/blogs': {
      id: '/_public/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof PublicBlogsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/new-password': {
      id: '/_auth/new-password'
      path: '/new-password'
      fullPath: '/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password-otp': {
      id: '/_auth/forgot-password-otp'
      path: '/forgot-password-otp'
      fullPath: '/forgot-password-otp'
      preLoaderRoute: typeof AuthForgotPasswordOtpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_public/integrations/': {
      id: '/_public/integrations/'
      path: '/'
      fullPath: '/integrations/'
      preLoaderRoute: typeof PublicIntegrationsIndexRouteImport
      parentRoute: typeof PublicIntegrationsRoute
    }
    '/_public/features/': {
      id: '/_public/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof PublicFeaturesIndexRouteImport
      parentRoute: typeof PublicFeaturesRoute
    }
    '/_public/blogs/': {
      id: '/_public/blogs/'
      path: '/'
      fullPath: '/blogs/'
      preLoaderRoute: typeof PublicBlogsIndexRouteImport
      parentRoute: typeof PublicBlogsRoute
    }
    '/_public/integrations/$slug': {
      id: '/_public/integrations/$slug'
      path: '/$slug'
      fullPath: '/integrations/$slug'
      preLoaderRoute: typeof PublicIntegrationsSlugRouteImport
      parentRoute: typeof PublicIntegrationsRoute
    }
    '/_public/features/$slug': {
      id: '/_public/features/$slug'
      path: '/$slug'
      fullPath: '/features/$slug'
      preLoaderRoute: typeof PublicFeaturesSlugRouteImport
      parentRoute: typeof PublicFeaturesRoute
    }
    '/_public/blogs/$slug': {
      id: '/_public/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof PublicBlogsSlugRouteImport
      parentRoute: typeof PublicBlogsRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthForgotPasswordOtpRoute: typeof AuthForgotPasswordOtpRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthForgotPasswordOtpRoute: AuthForgotPasswordOtpRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface PublicBlogsRouteChildren {
  PublicBlogsSlugRoute: typeof PublicBlogsSlugRoute
  PublicBlogsIndexRoute: typeof PublicBlogsIndexRoute
}

const PublicBlogsRouteChildren: PublicBlogsRouteChildren = {
  PublicBlogsSlugRoute: PublicBlogsSlugRoute,
  PublicBlogsIndexRoute: PublicBlogsIndexRoute,
}

const PublicBlogsRouteWithChildren = PublicBlogsRoute._addFileChildren(
  PublicBlogsRouteChildren,
)

interface PublicFeaturesRouteChildren {
  PublicFeaturesSlugRoute: typeof PublicFeaturesSlugRoute
  PublicFeaturesIndexRoute: typeof PublicFeaturesIndexRoute
}

const PublicFeaturesRouteChildren: PublicFeaturesRouteChildren = {
  PublicFeaturesSlugRoute: PublicFeaturesSlugRoute,
  PublicFeaturesIndexRoute: PublicFeaturesIndexRoute,
}

const PublicFeaturesRouteWithChildren = PublicFeaturesRoute._addFileChildren(
  PublicFeaturesRouteChildren,
)

interface PublicIntegrationsRouteChildren {
  PublicIntegrationsSlugRoute: typeof PublicIntegrationsSlugRoute
  PublicIntegrationsIndexRoute: typeof PublicIntegrationsIndexRoute
}

const PublicIntegrationsRouteChildren: PublicIntegrationsRouteChildren = {
  PublicIntegrationsSlugRoute: PublicIntegrationsSlugRoute,
  PublicIntegrationsIndexRoute: PublicIntegrationsIndexRoute,
}

const PublicIntegrationsRouteWithChildren =
  PublicIntegrationsRoute._addFileChildren(PublicIntegrationsRouteChildren)

interface PublicRouteRouteChildren {
  PublicBlogsRoute: typeof PublicBlogsRouteWithChildren
  PublicContactSalesRoute: typeof PublicContactSalesRoute
  PublicContactUsRoute: typeof PublicContactUsRoute
  PublicCookiePolicyRoute: typeof PublicCookiePolicyRoute
  PublicFeaturesRoute: typeof PublicFeaturesRouteWithChildren
  PublicIntegrationsRoute: typeof PublicIntegrationsRouteWithChildren
  PublicPricingRoute: typeof PublicPricingRoute
  PublicPrivacyPolicyRoute: typeof PublicPrivacyPolicyRoute
  PublicRequestDemoRoute: typeof PublicRequestDemoRoute
  PublicTermsOfServiceRoute: typeof PublicTermsOfServiceRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicBlogsRoute: PublicBlogsRouteWithChildren,
  PublicContactSalesRoute: PublicContactSalesRoute,
  PublicContactUsRoute: PublicContactUsRoute,
  PublicCookiePolicyRoute: PublicCookiePolicyRoute,
  PublicFeaturesRoute: PublicFeaturesRouteWithChildren,
  PublicIntegrationsRoute: PublicIntegrationsRouteWithChildren,
  PublicPricingRoute: PublicPricingRoute,
  PublicPrivacyPolicyRoute: PublicPrivacyPolicyRoute,
  PublicRequestDemoRoute: PublicRequestDemoRoute,
  PublicTermsOfServiceRoute: PublicTermsOfServiceRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
  ApiContactRoute: ApiContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
